services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my_secure_password   # Set the password directly here
      MYSQL_DATABASE: mastersgtp?createDatabaseIfNotExist=true
      MYSQL_PASSWORD: my_secure_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mastersgtp-network
    pull_policy: never

  backend:
    build:
      context: ./mastersgtp
      dockerfile: Dockerfile
    image: mastersgtp-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mastersgtp?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=my_secure_password
    depends_on:
      - mysql
    networks:
      - mastersgtp-network
    restart: unless-stopped
    pull_policy: never

  frontend:
    build:
      context: ./mastersgtp-frontend
      dockerfile: Dockerfile
    image: mastersgtp-frontend:latest
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - mastersgtp-network
    pull_policy: never

networks:
  mastersgtp-network:
    driver: bridge

volumes:
  mysql_data: