services:
  backend:
    image: mastersgtp-backend:latest       # Use the prebuilt backend image
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/mastersgtp?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    networks:
      - mastersgtp-network
    restart: unless-stopped
    deploy:
      update_config:
        delay: 0s
      restart_policy:
        condition: none

  frontend:
    image: mastersgtp-frontend:latest      # Use the prebuilt frontend image
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - mastersgtp-network
    deploy:
      update_config:
        delay: 0s
      restart_policy:
        condition: none

networks:
  mastersgtp-network:
    driver: bridge